### ISSUE TITLE
Store text blocks in content/ folder

### ISSUE THREAD

**Issue by cmb69** [cmb69/boilerplate_xh#1]
It seems to be reasonable to store the text blocks in the general content/ folder, for easier handling by the user (backups etc.).

It has to be decided if the respective config option will be dropped or kept.

**Comment by cmb69** [comment]
It doesn't make much sense to make this path configurable. Well, language specific vs. general text blocks may make sense, but for backward compatibility with blocks for different languages, we stick with general text blocks, so users can simply move existing blocks to `content/boilerplate/`.

**Comment by olape-git** [comment]
> It doesn't make much sense to make this path configurable

:-(

**Comment by cmb69** [comment]
What's the problem?

**Comment by olape-git** [comment]
I have shares for external access to the files (via Remotecontent_XH for Hartmut).
This will no longer work under /content.

**Comment by cmb69** [comment]
If you don't mind that these files are publicly accessible, then you could add content/boilerplate/.htaccess with respective directives. If the changed URLs are an issue, you could set up redirects, or maybe just symlink the old location to content/boilerplate/.

My reasoning for this change is that all contents should be put in the contents folder, so (a) user can easily do a backup, and (b) the contents are protected from access.

**Comment by olape-git** [comment]
> If you don't mind that these files are publicly accessible, then you could add content/boilerplate/.htaccess with respective directives.

I think that will not work because of the .htaccess in /content.
I have a respective .htaccess, but currently under /userfiles/... (See explanation at https://olaf.penschke.net/?CMSimple_XH/Plugins/Remotecontent_XH) in which the access to the files is regulated.

But I can also adjust the path in Boilerplate again.

**Comment by olape-git** [comment]
Please create xml for Repo.

**Comment by cmb69** [comment]
[teplad.xml](https://github.com/cmb69/boilerplate_xh/blob/master/teplad.xml) is there, but I forgot where to submit. :(

**Comment by olape-git** [comment]
https://github.com/cmb69/boilerplate_xh/blob/a9ac4d705dddd3ea7834bd83b4d9a597c035990b/index.php#L25

1.0 ?

**Comment by cmb69** [comment]
> 1.0 ?

Oops! Danke, korrigiert.
